export const home = <i className="fa-solid fa-house"></i>;
export const heartEmpty = <i className="fa-regular fa-heart"></i>;
export const heartFilled = <i className="fa-solid fa-heart"></i>;
export const bookmarkEmpty = <i className="fa-regular fa-bookmark"></i>;
export const bookmarkFilled = <i className="fa-solid fa-bookmark"></i>;
export const arrowAngleRight = <i className="fa-solid fa-angle-right"></i>;
export const volumeHigh = <i className="fa-solid fa-volume-up"></i>;
export const arrowAngleDown = <i className="fa-solid fa-chevron-down"></i>;
export const search = <i className="fa-solid fa-magnifying-glass"></i>;